import type { Product, Order } from './types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name_en: 'Fresh Apples',
    name_bn: 'তাজা আপেল',
    sku: 'FRT-APL-01',
    unit: 'kg',
    stock_quantity: 100,
    selling_price: 250,
    buying_price: 180,
    category: 'Fruits',
    low_stock_threshold: 10,
    imageUrl: 'https://placehold.co/300x300.png',
  },
  {
    id: 'prod_002',
    name_en: 'Whole Milk',
    name_bn: 'পূর্ণ দুধ',
    sku: 'DRY-MLK-01',
    unit: 'pcs',
    stock_quantity: 50,
    selling_price: 120,
    buying_price: 90,
    category: 'Dairy',
    low_stock_threshold: 5,
    imageUrl: 'https://placehold.co/300x300.png',
  },
  {
    id: 'prod_003',
    name_en: 'Brown Bread',
    name_bn: 'বাদামী রুটি',
    sku: 'BKY-BRD-01',
    unit: 'pcs',
    stock_quantity: 30,
    selling_price: 80,
    buying_price: 50,
    category: 'Bakery',
    low_stock_threshold: 6,
    imageUrl: 'https://placehold.co/300x300.png',
  },
  {
    id: 'prod_004',
    name_en: 'Chicken Breast',
    name_bn: 'মুরগির বুকের মাংস',
    sku: 'MT-CKN-01',
    unit: 'kg',
    stock_quantity: 25,
    selling_price: 450,
    buying_price: 350,
    category: 'Meat',
    low_stock_threshold: 5,
    imageUrl: 'https://placehold.co/300x300.png',
  },
  {
    id: 'prod_005',
    name_en: 'Carrots',
    name_bn: 'গাজর',
    sku: 'VEG-CRT-01',
    unit: 'kg',
    stock_quantity: 80,
    selling_price: 60,
    buying_price: 40,
    category: 'Vegetables',
    low_stock_threshold: 15,
    imageUrl: 'https://placehold.co/300x300.png',
  },
  {
    id: 'prod_006',
    name_en: 'Organic Eggs',
    name_bn: 'জৈব ডিম',
    sku: 'DRY-EGG-01',
    unit: 'pcs',
    stock_quantity: 60,
    selling_price: 15,
    buying_price: 10,
    category: 'Dairy',
    low_stock_threshold: 12,
    imageUrl: 'https://placehold.co/300x300.png',
  },
  {
    id: 'prod_007',
    name_en: 'Lentils',
    name_bn: 'মসুর ডাল',
    sku: 'GRN-LNT-01',
    unit: 'kg',
    stock_quantity: 200,
    selling_price: 140,
    buying_price: 110,
    category: 'Grains',
    low_stock_threshold: 20,
    imageUrl: 'https://placehold.co/300x300.png',
  },
  {
    id: 'prod_008',
    name_en: 'Olive Oil',
    name_bn: 'জলপাই তেল',
    sku: 'OIL-OLV-01',
    unit: 'pcs',
    stock_quantity: 40,
    selling_price: 900,
    buying_price: 750,
    category: 'Pantry',
    low_stock_threshold: 8,
    imageUrl: 'https://placehold.co/300x300.png',
  },
];

export const orders: Order[] = [
    {
        id: 'ORD-001',
        items: [
            { product: products[0], quantity: 2, subtotal: 500, profit: 140 },
            { product: products[2], quantity: 1, subtotal: 80, profit: 30 },
        ],
        subtotal: 580,
        tax: 29,
        discount: 0,
        total: 609,
        totalProfit: 170,
        paymentMethod: 'cash',
        cashierId: 'cashier_01',
        createdAt: new Date(new Date().setDate(new Date().getDate() - 1)),
    },
    {
        id: 'ORD-002',
        items: [
            { product: products[3], quantity: 1.5, subtotal: 675, profit: 150 },
            { product: products[4], quantity: 3, subtotal: 180, profit: 60 },
        ],
        subtotal: 855,
        tax: 42.75,
        discount: 50,
        total: 847.75,
        totalProfit: 210,
        paymentMethod: 'card',
        cashierId: 'cashier_02',
        createdAt: new Date(),
    }
];
